//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticias
    {
        public int IdNoticia { get; set; }
        public string NombreNoticia { get; set; }
        public string CuerpoNoticia { get; set; }
    }
}
