//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoPendiente
    {
        public int IdPagoPendiente { get; set; }
        public double totalPago { get; set; }
        public int CedulaEnMora { get; set; }
    }
}
